{
  "openapi": "3.0.0",
  "info": {
    "contact": {
      "email": "support@datadoghq.com",
      "name": "Datadog Support",
      "url": "https://www.datadoghq.com/support/"
    },
    "description": "Collection of all Datadog Public endpoints.",
    "title": "Datadog API V2 Collection",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://{subdomain}.{site}",
      "variables": {
        "site": {
          "default": "datadoghq.com",
          "description": "The regional site for Datadog customers.",
          "enum": [
            "datadoghq.com",
            "us3.datadoghq.com",
            "us5.datadoghq.com",
            "ap1.datadoghq.com",
            "ap2.datadoghq.com",
            "uk1.datadoghq.com",
            "datadoghq.eu",
            "ddog-gov.com",
            "us2.ddog-gov.com",
            "uk1.datadoghq.com"
          ]
        },
        "subdomain": {
          "default": "api",
          "description": "The subdomain where the API is deployed."
        }
      }
    },
    {
      "url": "{protocol}://{name}",
      "variables": {
        "name": {
          "default": "api.datadoghq.com",
          "description": "Full site DNS name."
        },
        "protocol": {
          "default": "https",
          "description": "The protocol for accessing the API."
        }
      }
    },
    {
      "url": "https://{subdomain}.{site}",
      "variables": {
        "site": {
          "default": "datadoghq.com",
          "description": "Any Datadog deployment."
        },
        "subdomain": {
          "default": "api",
          "description": "The subdomain where the API is deployed."
        }
      }
    }
  ],
  "tags": [
    {
      "description": "The metrics endpoint allows you to:\n\n- Post metrics data so it can be graphed on Datadog\u2019s dashboards\n- Query metrics from any time period (timeseries and scalar)\n- Modify tag configurations for metrics\n- View tags and volumes for metrics\n\n**Note**: A graph can only contain a set number of points\nand as the timeframe over which a metric is viewed increases,\naggregation between points occurs to stay below that set number.\n\nThe Post, Patch, and Delete `manage_tags` API methods can only be performed by\na user who has the `Manage Tags for Metrics` permission.\n\nSee the [Metrics page](https://docs.datadoghq.com/metrics/) for more information.",
      "name": "Metrics",
      "x-datadog-tf-generator": {
        "derived_metric": {
          "resource": {
            "group": {
              "create": "CreateDerivedMetric",
              "delete": "DeleteDerivedMetric",
              "read": "GetDerivedMetric",
              "update": "UpdateDerivedMetric"
            },
            "tf_description": "Manages a derived metric computed from a formula and metric queries."
          }
        }
      }
    }
  ],
  "paths": {
    "/api/v2/metrics/derived-metrics": {
      "post": {
        "description": "Create a derived metric for the org. The metric name is supplied as the resource `id`,\nand the `definition` sets the formula and the queries the formula is computed from.\nRequires the `Manage Tags for Metrics` permission.",
        "operationId": "CreateDerivedMetric",
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "default": {
                  "value": {
                    "data": {
                      "attributes": {
                        "definition": {
                          "formula": "a",
                          "queries": [
                            {
                              "data_source": "metrics",
                              "name": "a",
                              "query": "avg:system.cpu.user{*}"
                            }
                          ]
                        }
                      },
                      "id": "my.derived.metric",
                      "type": "derived_metrics"
                    }
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/DerivedMetricCreateRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "data": {
                        "attributes": {
                          "definition": {
                            "formula": "a",
                            "queries": [
                              {
                                "data_source": "metrics",
                                "name": "a",
                                "query": "avg:system.cpu.user{*}"
                              }
                            ]
                          }
                        },
                        "id": "my.derived.metric",
                        "type": "derived_metrics"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/DerivedMetricResponse"
                }
              }
            },
            "description": "Created",
            "headers": {
              "Location": {
                "description": "The URL of the newly created derived metric.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "403": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Forbidden"
          },
          "409": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Conflict"
          },
          "429": {
            "$ref": "#/components/responses/TooManyRequestsResponse"
          }
        },
        "security": [
          {
            "apiKeyAuth": [],
            "appKeyAuth": []
          },
          {
            "AuthZ": [
              "metric_tags_write"
            ]
          }
        ],
        "summary": "Create a derived metric",
        "tags": [
          "Metrics"
        ],
        "x-codegen-request-body-name": "body",
        "x-datadog-generators": {
          "generators": {
            "terraform": true
          }
        },
        "x-permission": {
          "operator": "OR",
          "permissions": [
            "metric_tags_write"
          ]
        }
      }
    },
    "/api/v2/metrics/derived-metrics/{metric_name}": {
      "delete": {
        "description": "Delete a derived metric by name. Idempotent: returns 204 regardless of whether the derived\nmetric existed. Requires the `Manage Tags for Metrics` permission.",
        "operationId": "DeleteDerivedMetric",
        "parameters": [
          {
            "$ref": "#/components/parameters/MetricName"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "429": {
            "$ref": "#/components/responses/TooManyRequestsResponse"
          }
        },
        "security": [
          {
            "apiKeyAuth": [],
            "appKeyAuth": []
          },
          {
            "AuthZ": [
              "metric_tags_write"
            ]
          }
        ],
        "summary": "Delete a derived metric",
        "tags": [
          "Metrics"
        ],
        "x-datadog-generators": {
          "generators": {
            "terraform": true
          }
        },
        "x-permission": {
          "operator": "OR",
          "permissions": [
            "metric_tags_write"
          ]
        }
      },
      "get": {
        "description": "Get the definition of a derived metric by name.",
        "operationId": "GetDerivedMetric",
        "parameters": [
          {
            "$ref": "#/components/parameters/MetricName"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "data": {
                        "attributes": {
                          "definition": {
                            "formula": "a",
                            "queries": [
                              {
                                "data_source": "metrics",
                                "name": "a",
                                "query": "avg:system.cpu.user{*}"
                              }
                            ]
                          }
                        },
                        "id": "my.derived.metric",
                        "type": "derived_metrics"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/DerivedMetricResponse"
                }
              }
            },
            "description": "OK"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Not Found"
          },
          "429": {
            "$ref": "#/components/responses/TooManyRequestsResponse"
          }
        },
        "security": [
          {
            "apiKeyAuth": [],
            "appKeyAuth": []
          },
          {
            "AuthZ": [
              "metrics_read"
            ]
          }
        ],
        "summary": "Get a derived metric",
        "tags": [
          "Metrics"
        ],
        "x-datadog-generators": {
          "generators": {
            "terraform": true
          }
        },
        "x-permission": {
          "operator": "OR",
          "permissions": [
            "metrics_read"
          ]
        }
      },
      "put": {
        "description": "Update the definition of an existing derived metric. The `id` in the request body\nmust match the `metric_name` path parameter. Requires the `Manage Tags for Metrics` permission.",
        "operationId": "UpdateDerivedMetric",
        "parameters": [
          {
            "$ref": "#/components/parameters/MetricName"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "default": {
                  "value": {
                    "data": {
                      "attributes": {
                        "definition": {
                          "formula": "a",
                          "queries": [
                            {
                              "data_source": "metrics",
                              "name": "a",
                              "query": "avg:system.cpu.user{*}"
                            }
                          ]
                        }
                      },
                      "id": "my.derived.metric",
                      "type": "derived_metrics"
                    }
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/DerivedMetricCreateRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "default": {
                    "value": {
                      "data": {
                        "attributes": {
                          "definition": {
                            "formula": "a",
                            "queries": [
                              {
                                "data_source": "metrics",
                                "name": "a",
                                "query": "avg:system.cpu.user{*}"
                              }
                            ]
                          }
                        },
                        "id": "my.derived.metric",
                        "type": "derived_metrics"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/DerivedMetricResponse"
                }
              }
            },
            "description": "OK"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Bad Request"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIErrorResponse"
                }
              }
            },
            "description": "Not Found"
          },
          "429": {
            "$ref": "#/components/responses/TooManyRequestsResponse"
          }
        },
        "security": [
          {
            "apiKeyAuth": [],
            "appKeyAuth": []
          },
          {
            "AuthZ": [
              "metric_tags_write"
            ]
          }
        ],
        "summary": "Update a derived metric",
        "tags": [
          "Metrics"
        ],
        "x-codegen-request-body-name": "body",
        "x-datadog-generators": {
          "generators": {
            "terraform": true
          }
        },
        "x-permission": {
          "operator": "OR",
          "permissions": [
            "metric_tags_write"
          ]
        }
      }
    }
  },
  "components": {
    "schemas": {
      "DerivedMetricCreateRequest": {
        "description": "Request body for creating or updating a derived metric.",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/DerivedMetricCreateData"
          }
        },
        "required": [
          "data"
        ],
        "type": "object"
      },
      "DerivedMetricCreateData": {
        "description": "Data object for creating or updating a derived metric.",
        "properties": {
          "attributes": {
            "$ref": "#/components/schemas/DerivedMetricAttributes"
          },
          "id": {
            "description": "The derived metric name used as the resource ID.",
            "example": "my.derived.metric",
            "type": "string"
          },
          "type": {
            "$ref": "#/components/schemas/DerivedMetricsType"
          }
        },
        "required": [
          "id",
          "type",
          "attributes"
        ],
        "type": "object"
      },
      "DerivedMetricAttributes": {
        "description": "Attributes of a derived metric.",
        "properties": {
          "definition": {
            "$ref": "#/components/schemas/DerivedMetricDefinition"
          }
        },
        "required": [
          "definition"
        ],
        "type": "object"
      },
      "DerivedMetricDefinition": {
        "description": "The definition of a derived metric as a formula over one or more queries.",
        "properties": {
          "formula": {
            "description": "The formula that combines the queries into the value of the derived metric.",
            "example": "a",
            "type": "string"
          },
          "queries": {
            "description": "The list of queries referenced by the formula.",
            "items": {
              "$ref": "#/components/schemas/DerivedMetricQuery"
            },
            "minItems": 1,
            "type": "array"
          }
        },
        "required": [
          "formula",
          "queries"
        ],
        "type": "object"
      },
      "DerivedMetricQuery": {
        "description": "A single query used in the definition of a derived metric.",
        "properties": {
          "data_source": {
            "description": "The data source that the query is run against.",
            "example": "metrics",
            "type": "string"
          },
          "name": {
            "description": "The name used to reference this query from the formula.",
            "example": "a",
            "type": "string"
          },
          "query": {
            "description": "The query string executed against the data source.",
            "example": "avg:system.cpu.user{*}",
            "type": "string"
          }
        },
        "required": [
          "data_source",
          "name",
          "query"
        ],
        "type": "object"
      },
      "DerivedMetricsType": {
        "default": "derived_metrics",
        "description": "The derived metric resource type.",
        "enum": [
          "derived_metrics"
        ],
        "example": "derived_metrics",
        "type": "string",
        "x-enum-varnames": [
          "DERIVED_METRICS"
        ]
      },
      "DerivedMetricResponse": {
        "description": "Response containing a single derived metric.",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/DerivedMetricData"
          }
        },
        "readOnly": true,
        "required": [
          "data"
        ],
        "type": "object"
      },
      "DerivedMetricData": {
        "description": "A derived metric resource object.",
        "properties": {
          "attributes": {
            "$ref": "#/components/schemas/DerivedMetricAttributes"
          },
          "id": {
            "description": "The derived metric name used as the resource ID.",
            "example": "my.derived.metric",
            "type": "string"
          },
          "type": {
            "$ref": "#/components/schemas/DerivedMetricsType"
          }
        },
        "required": [
          "id",
          "type",
          "attributes"
        ],
        "type": "object"
      },
      "APIErrorResponse": {
        "description": "API error response.",
        "properties": {
          "errors": {
            "description": "A list of errors.",
            "example": [
              "Bad Request"
            ],
            "items": {
              "description": "A list of items.",
              "example": "Bad Request",
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "errors"
        ],
        "type": "object"
      }
    },
    "responses": {
      "TooManyRequestsResponse": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/APIErrorResponse"
            }
          }
        },
        "description": "Too many requests"
      }
    },
    "parameters": {
      "MetricName": {
        "description": "The name of the metric.",
        "example": "dist.http.endpoint.request",
        "in": "path",
        "name": "metric_name",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    }
  }
}
